inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

# Craches in RuboCop 0.53.0
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

# Easier to turn off, until I figure out how to change the behavior of Emacs.
Style/Encoding:
  Enabled: false

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses

Style/NumericPredicate:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 5

Naming/PredicateName:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - test_*.rb

Metrics/MethodLength:
  Exclude:
    - test_*.rb

Metrics/AbcSize:
  Exclude:
    - test_*.rb

Style/MultipleComparison:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Layout/LineLength:
  Max: 80

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true
 
Naming/VariableNumber:
  EnforcedStyle: snake_case
